---

- name: 'Show simple message on all hosts'
  hosts: all
  become: true
  tasks:
    - name: 'Say Hello'
      shell: 'echo Hello and die!'
      register: my_shell_cmd
      tags:
        - one

    - name: 'Show output of shell command'
      debug:
        msg: '{{ my_shell_cmd.stdout_lines }}'
      tags:
        - one
        - two
